/-
ChargeKernel.GoldenTraces — GENERATED by kernel/emit_lean_traces.py. Do not
edit; re-emit. Each trace below is the OBSERVED behavior of the Python
reference (accountant.py, SPEC §2.2 steps A-E) on a deterministic scenario
battery, replayed against the Lean model by `rfl`: per-step verdicts
(runReasons) and final account (run). If accountant.py and the model ever
disagree on any golden trace, this file stops compiling. Re-emission is
pinned byte-identical by test_kernel.py.
-/
import ChargeKernel.Basic

namespace ChargeKernel

-- emit_once
example : runReasons ({ entropy := 100000, ceiling := 1000000 } : Account) [{ admissible := true, bits := 80000 }] = [.emitted] := rfl
example : run ({ entropy := 100000, ceiling := 1000000 } : Account) [{ admissible := true, bits := 80000 }] = { entropy := 100000, ceiling := 1000000, cumulative := 80000, demanded := 80000, blocked := false, incident := true } := rfl

-- spec4_worked_example
example : runReasons ({ entropy := 100000, ceiling := 1000000 } : Account) [{ admissible := true, bits := 80000 }, { admissible := true, bits := 80000 }] = [.emitted, .emitted] := rfl
example : run ({ entropy := 100000, ceiling := 1000000 } : Account) [{ admissible := true, bits := 80000 }, { admissible := true, bits := 80000 }] = { entropy := 100000, ceiling := 1000000, cumulative := 160000, demanded := 160000, blocked := false, incident := true } := rfl

-- exact_remaining_then_blocked
example : runReasons ({ entropy := 100, ceiling := 50 } : Account) [{ admissible := true, bits := 20 }, { admissible := true, bits := 30 }, { admissible := true, bits := 1 }] = [.emitted, .emitted, .refusedBlocked] := rfl
example : run ({ entropy := 100, ceiling := 50 } : Account) [{ admissible := true, bits := 20 }, { admissible := true, bits := 30 }, { admissible := true, bits := 1 }] = { entropy := 100, ceiling := 50, cumulative := 50, demanded := 51, blocked := true, incident := false } := rfl

-- refuse_ceiling_then_blocked
example : runReasons ({ entropy := 100, ceiling := 50 } : Account) [{ admissible := true, bits := 60 }, { admissible := true, bits := 1 }] = [.refusedCeiling, .refusedBlocked] := rfl
example : run ({ entropy := 100, ceiling := 50 } : Account) [{ admissible := true, bits := 60 }, { admissible := true, bits := 1 }] = { entropy := 100, ceiling := 50, cumulative := 0, demanded := 61, blocked := true, incident := false } := rfl

-- inadmissible_accrues_nothing
example : runReasons ({ entropy := 100, ceiling := 50 } : Account) [{ admissible := false, bits := 999 }, { admissible := true, bits := 10 }, { admissible := false, bits := 999 }] = [.refusedEstimator, .emitted, .refusedEstimator] := rfl
example : run ({ entropy := 100, ceiling := 50 } : Account) [{ admissible := false, bits := 999 }, { admissible := true, bits := 10 }, { admissible := false, bits := 999 }] = { entropy := 100, ceiling := 50, cumulative := 10, demanded := 10, blocked := false, incident := false } := rfl

-- incident_at_exact_threshold
example : runReasons ({ entropy := 1000, ceiling := 5000 } : Account) [{ admissible := true, bits := 800 }] = [.emitted] := rfl
example : run ({ entropy := 1000, ceiling := 5000 } : Account) [{ admissible := true, bits := 800 }] = { entropy := 1000, ceiling := 5000, cumulative := 800, demanded := 800, blocked := false, incident := true } := rfl

-- incident_one_below_threshold
example : runReasons ({ entropy := 1000, ceiling := 5000 } : Account) [{ admissible := true, bits := 799 }] = [.emitted] := rfl
example : run ({ entropy := 1000, ceiling := 5000 } : Account) [{ admissible := true, bits := 799 }] = { entropy := 1000, ceiling := 5000, cumulative := 799, demanded := 799, blocked := false, incident := false } := rfl

-- incident_on_refused_demand
example : runReasons ({ entropy := 1000, ceiling := 100 } : Account) [{ admissible := true, bits := 900 }] = [.refusedCeiling] := rfl
example : run ({ entropy := 1000, ceiling := 100 } : Account) [{ admissible := true, bits := 900 }] = { entropy := 1000, ceiling := 100, cumulative := 0, demanded := 900, blocked := true, incident := true } := rfl

-- incident_while_blocked
example : runReasons ({ entropy := 1000, ceiling := 10 } : Account) [{ admissible := true, bits := 10 }, { admissible := true, bits := 790 }, { admissible := true, bits := 100 }] = [.emitted, .refusedBlocked, .refusedBlocked] := rfl
example : run ({ entropy := 1000, ceiling := 10 } : Account) [{ admissible := true, bits := 10 }, { admissible := true, bits := 790 }, { admissible := true, bits := 100 }] = { entropy := 1000, ceiling := 10, cumulative := 10, demanded := 900, blocked := true, incident := true } := rfl

-- zero_ceiling_first_emit_blocks
example : runReasons ({ entropy := 100, ceiling := 0 } : Account) [{ admissible := true, bits := 0 }, { admissible := true, bits := 0 }] = [.emitted, .refusedBlocked] := rfl
example : run ({ entropy := 100, ceiling := 0 } : Account) [{ admissible := true, bits := 0 }, { admissible := true, bits := 0 }] = { entropy := 100, ceiling := 0, cumulative := 0, demanded := 0, blocked := true, incident := false } := rfl

-- zero_bits_charges
example : runReasons ({ entropy := 100, ceiling := 50 } : Account) [{ admissible := true, bits := 0 }, { admissible := true, bits := 0 }, { admissible := true, bits := 50 }, { admissible := true, bits := 0 }] = [.emitted, .emitted, .emitted, .refusedBlocked] := rfl
example : run ({ entropy := 100, ceiling := 50 } : Account) [{ admissible := true, bits := 0 }, { admissible := true, bits := 0 }, { admissible := true, bits := 50 }, { admissible := true, bits := 0 }] = { entropy := 100, ceiling := 50, cumulative := 50, demanded := 50, blocked := true, incident := false } := rfl

-- ceiling_equals_entropy
example : runReasons ({ entropy := 200, ceiling := 200 } : Account) [{ admissible := true, bits := 200 }, { admissible := true, bits := 1 }] = [.emitted, .refusedBlocked] := rfl
example : run ({ entropy := 200, ceiling := 200 } : Account) [{ admissible := true, bits := 200 }, { admissible := true, bits := 1 }] = { entropy := 200, ceiling := 200, cumulative := 200, demanded := 201, blocked := true, incident := true } := rfl

-- interleaved_all_reasons
example : runReasons ({ entropy := 1000, ceiling := 100 } : Account) [{ admissible := false, bits := 5 }, { admissible := true, bits := 60 }, { admissible := true, bits := 50 }, { admissible := false, bits := 5 }, { admissible := true, bits := 10 }, { admissible := true, bits := 700 }] = [.refusedEstimator, .emitted, .refusedCeiling, .refusedEstimator, .refusedBlocked, .refusedBlocked] := rfl
example : run ({ entropy := 1000, ceiling := 100 } : Account) [{ admissible := false, bits := 5 }, { admissible := true, bits := 60 }, { admissible := true, bits := 50 }, { admissible := false, bits := 5 }, { admissible := true, bits := 10 }, { admissible := true, bits := 700 }] = { entropy := 1000, ceiling := 100, cumulative := 60, demanded := 820, blocked := true, incident := true } := rfl

-- large_realistic_magnitudes
example : runReasons ({ entropy := 512000, ceiling := 120000 } : Account) [{ admissible := true, bits := 64585 }, { admissible := true, bits := 50000 }, { admissible := true, bits := 50000 }, { admissible := true, bits := 1000 }] = [.emitted, .emitted, .refusedCeiling, .refusedBlocked] := rfl
example : run ({ entropy := 512000, ceiling := 120000 } : Account) [{ admissible := true, bits := 64585 }, { admissible := true, bits := 50000 }, { admissible := true, bits := 50000 }, { admissible := true, bits := 1000 }] = { entropy := 512000, ceiling := 120000, cumulative := 114585, demanded := 165585, blocked := true, incident := false } := rfl

end ChargeKernel
