"""Emit golden accountant traces AND their Lean replay (ASSURANCE.md L4).

The Lean kernel's honest limit was "model-code correspondence is by
construction, not by proof". This closes it MECHANICALLY: a deterministic
scenario battery runs through the REAL accountant.py (SPEC §2.2 steps A-E),
and the observed behavior — per-step verdicts and final account state — is
transcribed into ChargeKernel/GoldenTraces.lean, where every trace replays
by `rfl` against the Lean `step`/`run`/`runReasons` model. If accountant.py
and the Lean model ever disagree on any golden trace, `lake build` goes red.

Two artifacts, both committed:
    lean_traces/accountant_traces.json     language-neutral golden traces
    ../lean/ChargeKernel/GoldenTraces.lean generated Lean replay (rfl only —
                                           no new axioms, no tactics)

Determinism is pinned by test_kernel.py: re-emission must be byte-identical.

Run: python3 chambers/kernel/emit_lean_traces.py
"""
from __future__ import annotations

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from chambers.kernel.accountant import (  # noqa: E402
    Accountant,
    CapacityEstimate,
    EstimatorAttestation,
)

HERE = os.path.dirname(os.path.abspath(__file__))
JSON_OUT = os.path.join(HERE, "lean_traces", "accountant_traces.json")
LEAN_OUT = os.path.join(HERE, "..", "lean", "ChargeKernel", "GoldenTraces.lean")

ADMISSIBLE = EstimatorAttestation("indep", "adversarial_review", "m", True)
INADMISSIBLE = EstimatorAttestation("selfmeter", "self_interested", "m", True)

REASON_TO_LEAN = {
    "EMITTED": ".emitted",
    "REFUSED_ESTIMATOR": ".refusedEstimator",
    "REFUSED_BLOCKED": ".refusedBlocked",
    "REFUSED_CEILING": ".refusedCeiling",
}

# (name, entropy, ceiling, [(admissible, bits), ...]) — every SPEC §2.2
# branch and boundary the model must agree on.
SCENARIOS = [
    ("emit_once", 100000, 1000000, [(True, 80000)]),
    ("spec4_worked_example", 100000, 1000000, [(True, 80000), (True, 80000)]),
    ("exact_remaining_then_blocked", 100, 50, [(True, 20), (True, 30), (True, 1)]),
    ("refuse_ceiling_then_blocked", 100, 50, [(True, 60), (True, 1)]),
    ("inadmissible_accrues_nothing", 100, 50, [(False, 999), (True, 10), (False, 999)]),
    ("incident_at_exact_threshold", 1000, 5000, [(True, 800)]),
    ("incident_one_below_threshold", 1000, 5000, [(True, 799)]),
    ("incident_on_refused_demand", 1000, 100, [(True, 900)]),
    ("incident_while_blocked", 1000, 10, [(True, 10), (True, 790), (True, 100)]),
    ("zero_ceiling_first_emit_blocks", 100, 0, [(True, 0), (True, 0)]),
    ("zero_bits_charges", 100, 50, [(True, 0), (True, 0), (True, 50), (True, 0)]),
    ("ceiling_equals_entropy", 200, 200, [(True, 200), (True, 1)]),
    ("interleaved_all_reasons", 1000, 100,
     [(False, 5), (True, 60), (True, 50), (False, 5), (True, 10), (True, 700)]),
    ("large_realistic_magnitudes", 512000, 120000,
     [(True, 64585), (True, 50000), (True, 50000), (True, 1000)]),
]


def run_reference(entropy: int, ceiling: int, charges) -> dict:
    acc = Accountant()
    key = ("golden",)
    acc.register(key, entropy, ceiling)
    reasons = []
    for i, (adm, bits) in enumerate(charges):
        att = ADMISSIBLE if adm else INADMISSIBLE
        dec = acc.charge(key, CapacityEstimate(bits, 0, 0, 0, 0, "c"), att, tick=i)
        reasons.append(dec.reason_class)
    st = acc.state(key)
    return {
        "reasons": reasons,
        "final": {
            "cumulative": st.cumulative_mbits,
            "demanded": st.demanded_mbits,
            "blocked": st.blocked,
            "incident": st.incident,
        },
    }


def lean_bool(b: bool) -> str:
    return "true" if b else "false"


def emit() -> None:
    traces = []
    for name, entropy, ceiling, charges in SCENARIOS:
        expected = run_reference(entropy, ceiling, charges)
        traces.append({
            "name": name,
            "entropy": entropy,
            "ceiling": ceiling,
            "charges": [{"admissible": a, "bits": b} for a, b in charges],
            **expected,
        })

    os.makedirs(os.path.dirname(JSON_OUT), exist_ok=True)
    with open(JSON_OUT, "w", encoding="ascii") as fh:
        json.dump({"spec": "egress-accountant/1 §2.2", "traces": traces}, fh,
                  indent=1, sort_keys=True)
        fh.write("\n")

    lines = [
        "/-",
        "ChargeKernel.GoldenTraces — GENERATED by kernel/emit_lean_traces.py. Do not",
        "edit; re-emit. Each trace below is the OBSERVED behavior of the Python",
        "reference (accountant.py, SPEC §2.2 steps A-E) on a deterministic scenario",
        "battery, replayed against the Lean model by `rfl`: per-step verdicts",
        "(runReasons) and final account (run). If accountant.py and the model ever",
        "disagree on any golden trace, this file stops compiling. Re-emission is",
        "pinned byte-identical by test_kernel.py.",
        "-/",
        "import ChargeKernel.Basic",
        "",
        "namespace ChargeKernel",
        "",
    ]
    for t in traces:
        acct = f"{{ entropy := {t['entropy']}, ceiling := {t['ceiling']} }}"
        chs = ", ".join(
            f"{{ admissible := {lean_bool(c['admissible'])}, bits := {c['bits']} }}"
            for c in t["charges"]
        )
        reasons = ", ".join(REASON_TO_LEAN[r] for r in t["reasons"])
        fin = t["final"]
        final = (
            f"{{ entropy := {t['entropy']}, ceiling := {t['ceiling']}, "
            f"cumulative := {fin['cumulative']}, demanded := {fin['demanded']}, "
            f"blocked := {lean_bool(fin['blocked'])}, "
            f"incident := {lean_bool(fin['incident'])} }}"
        )
        lines += [
            f"-- {t['name']}",
            f"example : runReasons ({acct} : Account) [{chs}] = [{reasons}] := rfl",
            f"example : run ({acct} : Account) [{chs}] = {final} := rfl",
            "",
        ]
    lines += ["end ChargeKernel", ""]
    with open(LEAN_OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    print(f"{len(traces)} golden accountant traces -> {JSON_OUT}")
    print(f"lean replay -> {os.path.normpath(LEAN_OUT)}")


if __name__ == "__main__":
    emit()
